on:
  pull_request_review:
    types: [submitted]
    
env:
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
  

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          npm install
          npm run main --if-present
