on:
  pull_request:
    types:
      - closed
    
env:
  NODE_VERSION: '16.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ NODE_VERSION }}
            cache: 'npm'
            cache-dependency-path: subdir/package-lock.json
        - run: npm i
        - run: npm main
