on:
  pull_request:
    types:
      - closed
      
env:
  NODE_VERSION: '16' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
  

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          npm install
          npm run main --if-present
